cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('store.urls', namespace='store')),
]

""" Если устанговлен режим дебага True, то джанго будет брать медиа из папок которые мы указали. """
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from store.authorization.authorization import LoginUser, logout_user, RegisterUser
from store.views import Home, ProductsByCategory, GetProduct, ProductsByBrand

app_name = 'store'

urlpatterns = [
    path('', Home.as_view(), name='home'),

    path('category/<slug:slug>/', ProductsByCategory.as_view(), name='category'),
    path('product/<slug:slug>/', GetProduct.as_view(), name='product'),
    path('brand/<slug:slug>/', ProductsByBrand.as_view(), name='brand'),

    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

templates/inc/_footer.html
{% load menu %}

<footer class="footer" style="margin-top: 100px">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="footer-bg">
          <div class="row">
            <div class="col-md-9">
              {% show_menu 'footer-menu' %}
            </div>
            <div class="col-md-3">
              <div class="footer-icon">
                <p><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a><a href="#"><i
                        class="fa fa-twitter" aria-hidden="true"></i></a><a href="#"><i
                        class="fa fa-linkedin" aria-hidden="true"></i></a><a href="#"><i
                        class="fa fa-dribbble" aria-hidden="true"></i></a></p>
              </div>
            </div>
          </div>
          .
        </div>
      </div>
    </div>
  </div>
</footer>

templates/inc/_header.html
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <a href="/"><h3>Главная страница</h3></a>
            </div>

            <div class="col-sm-4" align="right">
                <div class="cart">
                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url 'cart:cart_detail' %}">
                        {{ total_items }} item{{ total_items|pluralize }},
                        ${{ cart.get_total_price }}
                    </a>
                    {% else %}
                    Your cart is empty.
                    {% endif %}
                    {% endwith %}
                </div>

            </div>

            <div class="col-sm-2">

                {% if request.user.is_authenticated %}

                <div class="last">{{ user.username }} | <a href="{% url 'store:logout' %}">Выйти</a></div>

                {% else %}

                <div class="last"><a href="{% url 'store:register' %}">Регистрация</a> | <a href="{% url 'store:login' %}">Войти</a>
                </div>

                {% endif %}
            </div>
        </div>

    </div>
    <hr>
</header>

templates/inc/_sidebar.html
{% load menu %}

{% show_menu %}